version: "3.9"

services:
  app:
    build: .
    container_name: logback-app
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    volumes:
      - app-logs:/app/logs
    depends_on:
      splunk:
        condition: service_healthy
    networks:
      - app-network

  splunk:
    image: splunk/splunk:9.2.0
    container_name: splunk
    ports:
      - "8000:8000"  # Splunk Web UI
      - "8089:8089"  # Splunk Management Port
      - "8088:8088"  # HTTP Event Collector (HEC)
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_PASSWORD: Chang3_Me!
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000 || exit 1"]
      interval: 30s
      timeout: 10s
      start_period: 180s
      retries: 10
    volumes:
      - splunk-etc:/opt/splunk/etc
      - splunk-var:/opt/splunk/var
    networks:
      - app-network

volumes:
  app-logs:
  splunk-etc:
  splunk-var:

networks:
  app-network:
    driver: bridge